# Generated by Django 5.1.2 on 2024-11-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_payment_status_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_send_email',
            field=models.BooleanField(default=False),
        ),
    ]
